# このファイルについて
- about: 
    1. 2kmピッチにトラカンが設置している区間情報を保存
        - 2023/8/17-2023/9/30のデータが授受の段階で当該区間に限定されているため、このデータを利用
        - 関越:
            - 上り: `大泉JCT〜昭和`
            - 下り: `大泉JCT〜沼田`
        - 東北:
            - 上り: `浦和〜白河`
            - 下り: `浦和〜矢板`
    2. 各区間の2kmトラカン基数を列挙
- author: 松永

In [1]:
import pickle
import pandas as pd

# 1. 2kmピッチにトラカンが設置している区間情報を保存

In [3]:
df_kannetsu = pd.read_csv(f'./traffic/raw_kannetsu_20230817-20230930_2KP.csv')
df_touhoku = pd.read_csv(f'./traffic/raw_touhoku_20230817-20230930_2KP.csv')

/opt/conda/envs/rapids/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3457: DtypeWarning: Columns (22,28,34,40) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/opt/conda/envs/rapids/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3457: DtypeWarning: Columns (22,28,34) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [25]:
tc_segments_kannetsu = df_kannetsu.loc[:, ['区間名称', '方向']].drop_duplicates()
tc_segments_touhoku = df_touhoku.loc[:, ['区間名称', '方向']].drop_duplicates()

In [97]:
tc_segments_kannetsu

                       区間名称  方向
0                大泉ＪＣＴ　〜　所沢  上り
64800       所沢　〜　三芳ＰＡスマートＩＣ  上り
90720       三芳ＰＡスマートＩＣ　〜　川越  上り
142560          川越　〜　鶴ヶ島ＪＣＴ  上り
194400         鶴ヶ島ＪＣＴ　〜　鶴ヶ島  上り
220320      鶴ヶ島　〜　坂戸西スマートＩＣ  上り
246240      坂戸西スマートＩＣ　〜　東松山  上り
311040           東松山　〜　嵐山小川  上り
362880            嵐山小川　〜　花園  上り
427680      花園　〜　寄居ＰＡスマートＩＣ  上り
492480    寄居ＰＡスマートＩＣ　〜　本庄児玉  上り
531360    本庄児玉　〜　上里ＳＡスマートＩＣ  上り
583200   上里ＳＡスマートＩＣ　〜　藤岡ＪＣＴ  上り
622080   藤岡ＪＣＴ　〜　高崎玉村スマートＩＣ  上り
635040   高崎玉村スマートＩＣ　〜　高崎ＪＣＴ  上り
660960           高崎ＪＣＴ　〜　高崎  上り
673920              高崎　〜　前橋  上り
699840      前橋　〜　駒寄ＰＡスマートＩＣ  上り
738720   駒寄ＰＡスマートＩＣ　〜　渋川伊香保  上り
777600           渋川伊香保　〜　赤城  上り
829440              赤城　〜　昭和  上り
894240           大泉ＪＣＴ　〜　所沢  下り
946080      所沢　〜　三芳ＰＡスマートＩＣ  下り
972000      三芳ＰＡスマートＩＣ　〜　川越  下り
1023840         川越　〜　鶴ヶ島ＪＣＴ  下り
1075680        鶴ヶ島ＪＣＴ　〜　鶴ヶ島  下り
1101600     鶴ヶ島　〜　坂戸西スマートＩＣ  下り
1127520     坂戸西スマートＩＣ　〜　東松山  下り
1192320          東松山　〜　嵐山小川  下り
1244160           嵐山小川　〜　花園  下り
1296000     花園　〜　寄居ＰＡスマートＩＣ  下り
1360800   寄居ＰＡスマートＩＣ　〜　本庄児玉  下り
1412640   本庄児玉　〜　上里ＳＡスマートＩＣ  下り
1451520  上里ＳＡスマートＩＣ　〜　藤岡ＪＣＴ  下り
1477440  藤岡ＪＣＴ　〜　高崎玉村スマートＩＣ  下り
1503360  高崎玉村スマートＩＣ　〜　高崎ＪＣＴ  下り
1516320          高崎ＪＣＴ　〜　高崎  下り
1529280             高崎　〜　前橋  下り
1555200     前橋　〜　駒寄ＰＡスマートＩＣ  下り
1607040  駒寄ＰＡスマートＩＣ　〜　渋川伊香保  下り
1632960          渋川伊香保　〜　赤城  下り
1684800             赤城　〜　昭和  下り
1749600             昭和　〜　沼田  下り

In [98]:
tc_segments_touhoku

                         区間名称  方向
0                     浦和　〜　岩槻  上り
38880         岩槻　〜　蓮田ＳＡスマートＩＣ  上り
90720    蓮田ＳＡスマートＩＣ　〜　久喜白岡ＪＣＴ  上り
129600                久喜　〜　加須  上り
194400                加須　〜　羽生  上り
233280                羽生　〜　館林  上り
285120              館林　〜　佐野藤岡  上り
349920      佐野藤岡　〜　佐野ＳＡスマートＩＣ  上り
362880     佐野ＳＡスマートＩＣ　〜　岩舟ＪＣＴ  上り
401760             岩舟ＪＣＴ　〜　栃木  上り
466560           栃木　〜　栃木都賀ＪＣＴ  上り
492480           栃木都賀ＪＣＴ　〜　鹿沼  上り
596160               鹿沼　〜　宇都宮  上り
673920      宇都宮　〜　上河内ＳＡスマートＩＣ  上り
725760       上河内ＳＡスマートＩＣ　〜　矢板  上り
790560         矢板　〜　矢板北スマートＩＣ  上り
842400     矢板北スマートＩＣ　〜　西那須野塩原  上り
920160          西那須野塩原　〜　黒磯板室  上り
959040              黒磯板室　〜　那須  上り
1010880     那須　〜　那須高原ＳＡスマートＩＣ  上り
1075680     那須高原ＳＡスマートＩＣ　〜　白河  上り
1127520               浦和　〜　岩槻  下り
1166400       岩槻　〜　蓮田ＳＡスマートＩＣ  下り
1218240  蓮田ＳＡスマートＩＣ　〜　久喜白岡ＪＣＴ  下り
1257120          久喜白岡ＪＣＴ　〜　久喜  下り
1270080               久喜　〜　加須  下り
1321920               加須　〜　羽生  下り
1360800               羽生　〜　館林  下り
1412640             館林　〜　佐野藤岡  下り
1477440     佐野藤岡　〜　佐野ＳＡスマートＩＣ  下り
1503360    佐野ＳＡスマートＩＣ　〜　岩舟ＪＣＴ  下り
1529280            岩舟ＪＣＴ　〜　栃木  下り
1594080          栃木　〜　栃木都賀ＪＣＴ  下り
1620000          栃木都賀ＪＣＴ　〜　鹿沼  下り
1723680              鹿沼　〜　宇都宮  下り
1801440     宇都宮　〜　上河内ＳＡスマートＩＣ  下り
1853280      上河内ＳＡスマートＩＣ　〜　矢板  下り

In [100]:
tc_segments_kannetsu_up = tc_segments_kannetsu.loc[tc_segments_kannetsu.方向 == '上り', '区間名称']
tc_segments_kannetsu_down = tc_segments_kannetsu.loc[tc_segments_kannetsu.方向 == '下り', '区間名称']

tc_segments_touhoku_up = tc_segments_touhoku.loc[tc_segments_touhoku.方向 == '上り', '区間名称']
tc_segments_touhoku_down = tc_segments_touhoku.loc[tc_segments_touhoku.方向 == '下り', '区間名称']

In [107]:
save_obj = {
    'kannetsu': {
        '上り': set(tc_segments_kannetsu_up),
        '下り': set(tc_segments_kannetsu_down),
    },
    'touhoku': {
        '上り': set(tc_segments_touhoku_up),
        '下り': set(tc_segments_touhoku_down),
    }
}

In [108]:
import pickle

with open('traffic_counter_segments_2KP.pkl', 'wb') as f:
    pickle.dump(save_obj, f)

# 2. 各区間の2kmトラカン基数を列挙

In [2]:
# TARGET_ROAD = 'kannetsu'
TARGET_ROAD = 'touhoku'

PERIOD = '20210401-20220331'

RAW_CSV = f'./traffic/raw_{TARGET_ROAD}_{PERIOD}_2KP.csv'
PROCESSED_CSV = f'./traffic/{TARGET_ROAD}_{PERIOD}_2KP.csv'

NUM_CSV = f'../../Input_processed_data/road_master/num_traffic_counter_2KP.csv'

## マスタデータ

In [3]:
df_master = pd.read_csv(NUM_CSV)
df_master.head()

       道路  方向                  区間名称  基数
0  東北自動車道  上り               浦和　〜　岩槻   3
1  東北自動車道  上り       岩槻　〜　蓮田ＳＡスマートＩＣ   4
2  東北自動車道  上り  蓮田ＳＡスマートＩＣ　〜　久喜白岡ＪＣＴ   3
3  東北自動車道  上り               久喜　〜　加須   5
4  東北自動車道  上り               加須　〜　羽生   3

In [4]:
if TARGET_ROAD == 'kannetsu':
    df_master = df_master.loc[df_master.道路 == '関越自動車道'].reset_index(drop=True)
elif TARGET_ROAD == 'touhoku':
    df_master = df_master.loc[df_master.道路 == '東北自動車道'].reset_index(drop=True)

In [5]:
print(df_master.shape)
df_master.head(3)

(37, 4)

       道路  方向                  区間名称  基数
0  東北自動車道  上り               浦和　〜　岩槻   3
1  東北自動車道  上り       岩槻　〜　蓮田ＳＡスマートＩＣ   4
2  東北自動車道  上り  蓮田ＳＡスマートＩＣ　〜　久喜白岡ＪＣＴ   3

### 区間名称の分割

In [6]:
def split_segment_name(df):
    # 全角スペースを除去 → "〜"で分割
    res = df.assign(segment_name=(df.区間名称.str.replace('\u3000', '').str.replace('\u3000', '').str.split('〜')))
    res = res.assign(
        start_name=res.segment_name.apply(lambda l: l[0]),
        end_name=res.segment_name.apply(lambda l: l[1])
    )
    return res

In [7]:
df_master = split_segment_name(df_master)
df_master.head()

,道路,方向,区間名称,基数,segment_name,start_name,end_name
0,東北自動車道,上り,浦和 〜 岩槻,3,"[浦和, 岩槻]",浦和,岩槻
1,東北自動車道,上り,岩槻 〜 蓮田ＳＡスマートＩＣ,4,"[岩槻, 蓮田ＳＡスマートＩＣ]",岩槻,蓮田ＳＡスマートＩＣ
2,東北自動車道,上り,蓮田ＳＡスマートＩＣ 〜 久喜白岡ＪＣＴ,3,"[蓮田ＳＡスマートＩＣ, 久喜白岡ＪＣＴ]",蓮田ＳＡスマートＩＣ,久喜白岡ＪＣＴ
3,東北自動車道,上り,久喜 〜 加須,5,"[久喜, 加須]",久喜,加須
4,東北自動車道,上り,加須 〜 羽生,3,"[加須, 羽生]",加須,羽生

### 上り区間・下り区間に応じて発着IC名を入れ替える
= 上り区間の発着IC名を入れ替える

In [8]:
def swap_start_end(df):
    up_start = df.loc[df.方向 == '上り', 'start_name']
    up_end = df.loc[df.方向 == '上り', 'end_name']

    df.loc[df.方向 == '上り', 'start_name'] = up_end
    df.loc[df.方向 == '上り', 'end_name'] = up_start
    
    return df

In [9]:
df_master = swap_start_end(df_master)
df_master.head()

,道路,方向,区間名称,基数,segment_name,start_name,end_name
0,東北自動車道,上り,浦和 〜 岩槻,3,"[浦和, 岩槻]",岩槻,浦和
1,東北自動車道,上り,岩槻 〜 蓮田ＳＡスマートＩＣ,4,"[岩槻, 蓮田ＳＡスマートＩＣ]",蓮田ＳＡスマートＩＣ,岩槻
2,東北自動車道,上り,蓮田ＳＡスマートＩＣ 〜 久喜白岡ＪＣＴ,3,"[蓮田ＳＡスマートＩＣ, 久喜白岡ＪＣＴ]",久喜白岡ＪＣＴ,蓮田ＳＡスマートＩＣ
3,東北自動車道,上り,久喜 〜 加須,5,"[久喜, 加須]",加須,久喜
4,東北自動車道,上り,加須 〜 羽生,3,"[加須, 羽生]",羽生,加須

### IC名称をICマスタデータに統一

In [10]:
IC_CSV = f'../../Input_processed_data/road_master/ic_preprocessed.csv'
IC_SUBNET_CSV = f'../../Input_processed_data/road_master/icnet_sub.csv'

In [11]:
df_ic = pd.read_csv(IC_CSV)
df_icnet = pd.read_csv(IC_SUBNET_CSV, dtype={'start_code': str, 'end_code': str, 'road_code': str})

# name => code
name2code = dict(zip(df_ic['ic_name'], df_ic['ic_code']))
name_traffic2code = dict(zip(df_ic['ic_name_traffic'], df_ic['ic_code']))
name2code.update(name_traffic2code)

# code => name
code2name = dict(zip(df_ic['ic_code'], df_ic['ic_name']))

In [12]:
def convert_ic_name(df):
    # IC名をICコードに直す（トラカン固有のIC名を含む）
    res = df.assign(
        direction=df.方向.map({'上り': 'up', '下り': 'down'}),
        start_code=df.start_name.map(name2code),
        end_code=df.end_name.map(name2code))
    
    # ICコードからIC名称に変換
    res = res.assign(
        start_name=res.start_code.map(code2name),
        end_name=res.end_code.map(code2name))
    
    return res

In [13]:
df_master = convert_ic_name(df_master)
df_master.head()

,道路,方向,区間名称,基数,segment_name,start_name,end_name,direction,start_code,end_code
0,東北自動車道,上り,浦和 〜 岩槻,3,"[浦和, 岩槻]",岩槻,浦和本線,up,1040016,1040013
1,東北自動車道,上り,岩槻 〜 蓮田ＳＡスマートＩＣ,4,"[岩槻, 蓮田ＳＡスマートＩＣ]",蓮田スマート,岩槻,up,1040020,1040016
2,東北自動車道,上り,蓮田ＳＡスマートＩＣ 〜 久喜白岡ＪＣＴ,3,"[蓮田ＳＡスマートＩＣ, 久喜白岡ＪＣＴ]",久喜白岡ＪＣＴ,蓮田スマート,up,1040023,1040020
3,東北自動車道,上り,久喜 〜 加須,5,"[久喜, 加須]",加須,久喜,up,1040031,1040026
4,東北自動車道,上り,加須 〜 羽生,3,"[加須, 羽生]",羽生,加須,up,1040036,1040031

In [14]:
df_master = df_master.loc[:, ['区間名称', '方向', 'start_name', 'start_code', 'end_name', 'end_code', '基数']]
df_master.head()

                   区間名称  方向 start_name start_code end_name end_code  基数
0               浦和　〜　岩槻  上り         岩槻    1040016     浦和本線  1040013   3
1       岩槻　〜　蓮田ＳＡスマートＩＣ  上り     蓮田スマート    1040020       岩槻  1040016   4
2  蓮田ＳＡスマートＩＣ　〜　久喜白岡ＪＣＴ  上り    久喜白岡ＪＣＴ    1040023   蓮田スマート  1040020   3
3               久喜　〜　加須  上り         加須    1040031       久喜  1040026   5
4               加須　〜　羽生  上り         羽生    1040036       加須  1040031   3

## 元データ

In [15]:
df = pd.read_csv(RAW_CSV)

print(df.shape)
df.head(3)

ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.

In [19]:
df_count = (df.loc[:, ['区間名称', '方向', 'KP']]
            .drop_duplicates()
            .groupby(['区間名称', '方向'])
            .count()
            .reset_index()
            .sort_values('方向')
            .reset_index(drop=True))
df_count.head(3)

              区間名称  方向  KP
0  三芳ＰＡスマートＩＣ　〜　川越  上り   4
1       渋川伊香保　〜　赤城  上り   4
2        嵐山小川　〜　花園  上り   5

In [20]:
df_merged = df_count.merge(df_master, on=['区間名称', '方向'])
df_merged.head()

              区間名称  方向  KP start_name start_code end_name end_code  基数
0  三芳ＰＡスマートＩＣ　〜　川越  上り   4         川越    1800016     三芳ＰＡ  1800011   4
1       渋川伊香保　〜　赤城  上り   4         赤城    1800096    渋川伊香保  1800091   4
2        嵐山小川　〜　花園  上り   5         花園    1800051     嵐山小川  1800041   5
3      川越　〜　鶴ヶ島ＪＣＴ  上り   4     鶴ヶ島ＪＣＴ    1800021       川越  1800016   4
4  所沢　〜　三芳ＰＡスマートＩＣ  上り   2       三芳ＰＡ    1800011       所沢  1800006   2

In [21]:
(df_merged.KP == df_merged.基数).all()

True

In [22]:
df_merged.loc[df_merged.KP != df_merged.基数]

Empty DataFrame
Columns: [区間名称, 方向, KP, start_name, start_code, end_name, end_code, 基数]
Index: []

In [23]:
df_temp = df.loc[(df.区間名称 == '久喜白岡ＪＣＴ　〜　久喜') & (df.方向 == '下り'), ['年', '月', '日', '方向', 'KP', '区間名称']]
df_temp2 = df_temp.loc[(df_temp.年 == 2022) & (df_temp.月 == 4) & (df_temp.日 == 1)]
df_temp3 = df_temp.loc[(df_temp.年 == 2023) & (df_temp.月 == 7) & (df_temp.日 == 31)]

In [223]:
df_temp = df.loc[(df.区間名称 == '前橋　〜　駒寄ＰＡスマートＩＣ') & (df.方向 == '上り'), ['年', '月', '日', '方向', 'KP', '区間名称']]
df_temp2 = df_temp.loc[(df_temp.年 == 2022) & (df_temp.月 == 10) & (df_temp.日 == 1)]
df_temp3 = df_temp.loc[(df_temp.年 == 2023) & (df_temp.月 == 7) & (df_temp.日 == 31)]

In [228]:
print(df_temp2.shape)
df_temp2.head()

(288, 6)

             年  月  日  方向      KP          区間名称
14446368  2022  4  1  下り  25.365  久喜白岡ＪＣＴ　〜　久喜
14446369  2022  4  1  下り  25.365  久喜白岡ＪＣＴ　〜　久喜
14446370  2022  4  1  下り  25.365  久喜白岡ＪＣＴ　〜　久喜
14446371  2022  4  1  下り  25.365  久喜白岡ＪＣＴ　〜　久喜
14446372  2022  4  1  下り  25.365  久喜白岡ＪＣＴ　〜　久喜

In [229]:
print(df_temp3.shape)
df_temp3.head()

(288, 6)

             年  月   日  方向      KP          区間名称
14586336  2023  7  31  下り  25.365  久喜白岡ＪＣＴ　〜　久喜
14586337  2023  7  31  下り  25.365  久喜白岡ＪＣＴ　〜　久喜
14586338  2023  7  31  下り  25.365  久喜白岡ＪＣＴ　〜　久喜
14586339  2023  7  31  下り  25.365  久喜白岡ＪＣＴ　〜　久喜
14586340  2023  7  31  下り  25.365  久喜白岡ＪＣＴ　〜　久喜

In [230]:
print(df_temp.KP.unique())
print(df_temp2.KP.unique())
print(df_temp3.KP.unique())

[25.365]
[25.365]
[25.365]

In [231]:
df_temp.loc[df_temp.KP == 24.999].sort_values(['年', '月', '日']).reset_index(drop=True)

Empty DataFrame
Columns: [年, 月, 日, 方向, KP, 区間名称]
Index: []

In [145]:
df_temp.loc[df_temp.KP == 92.801].sort_values(['年', '月', '日']).reset_index(drop=True)

          年   月   日  方向      KP             区間名称
0      2022  12   1  上り  92.801  前橋　〜　駒寄ＰＡスマートＩＣ
1      2022  12   1  上り  92.801  前橋　〜　駒寄ＰＡスマートＩＣ
2      2022  12   1  上り  92.801  前橋　〜　駒寄ＰＡスマートＩＣ
3      2022  12   1  上り  92.801  前橋　〜　駒寄ＰＡスマートＩＣ
4      2022  12   1  上り  92.801  前橋　〜　駒寄ＰＡスマートＩＣ
...     ...  ..  ..  ..     ...              ...
69979  2023   7  31  上り  92.801  前橋　〜　駒寄ＰＡスマートＩＣ
69980  2023   7  31  上り  92.801  前橋　〜　駒寄ＰＡスマートＩＣ
69981  2023   7  31  上り  92.801  前橋　〜　駒寄ＰＡスマートＩＣ
69982  2023   7  31  上り  92.801  前橋　〜　駒寄ＰＡスマートＩＣ
69983  2023   7  31  上り  92.801  前橋　〜　駒寄ＰＡスマートＩＣ

[69984 rows x 6 columns]

## 加工済みデータ

In [16]:
df_traffic = pd.read_csv(PROCESSED_CSV, dtype={'start_code': str, 'end_code': str,})

print(df_traffic.shape)
df_traffic.head(3)

(15557760, 29)

,datetime,start_name,end_name,start_code,end_code,start_pref_code,end_pref_code,start_lat,end_lat,start_lng,...,lane_count,KP_distance,KP,start_KP,end_KP,direction,limit_speed,OCC,allCars,speed
0,2021-04-01 00:00:00,浦和本線,岩槻,1040013,1040016,11,11,35.89012,35.93470,139.723697,...,3,5.7,5.47,4.8,10.5,down,100.0,2.0,50.0,89.0
1,2021-04-01 00:00:00,岩槻,浦和本線,1040016,1040013,11,11,35.93470,35.89012,139.690750,...,3,5.7,5.60,10.5,4.8,up,100.0,5.0,95.0,80.0
2,2021-04-01 00:00:00,浦和本線,岩槻,1040013,1040016,11,11,35.89012,35.93470,139.723697,...,3,5.7,7.30,4.8,10.5,down,100.0,2.0,49.0,94.0

In [17]:
df_count = (df_traffic.loc[:, ['start_name', 'start_code', 'end_name', 'end_code', 'KP']]
            .drop_duplicates()
            .groupby(['start_code', 'start_name', 'end_code', 'end_name'])
            .count()
            .reset_index()
            .sort_values(['start_code', 'end_code'])
            .reset_index(drop=True))
df_count.head(3)

  start_code start_name end_code end_name  KP
0    1040013       浦和本線  1040016       岩槻   3
1    1040016         岩槻  1040013     浦和本線   3
2    1040016         岩槻  1040020   蓮田スマート   4

In [18]:
df_merged = df_count.merge(df_master, on=['start_code', 'start_name', 'end_code', 'end_name'])
df_merged.head()

  start_code start_name end_code end_name  KP                  区間名称  方向  基数
0    1040013       浦和本線  1040016       岩槻   3               浦和　〜　岩槻  下り   3
1    1040016         岩槻  1040013     浦和本線   3               浦和　〜　岩槻  上り   3
2    1040016         岩槻  1040020   蓮田スマート   4       岩槻　〜　蓮田ＳＡスマートＩＣ  下り   4
3    1040020     蓮田スマート  1040016       岩槻   4       岩槻　〜　蓮田ＳＡスマートＩＣ  上り   4
4    1040020     蓮田スマート  1040023  久喜白岡ＪＣＴ   3  蓮田ＳＡスマートＩＣ　〜　久喜白岡ＪＣＴ  下り   3

In [19]:
(df_merged.KP == df_merged.基数).all()

True